### ISSUE TITLE
Enforce `struct_ref` to be populated at the entity level and not at the chain level

### ISSUE THREAD

**Issue by brindakv** [ihmwg/python-ihm#148]
Some of the submitted files generated using python-ihm / IMP have `struct_ref` data populated at the chain level with duplicate rows with the same information. 

This table should be populated at the entity level and not at the chain level. 

FYI @benmwebb @neeleshsoni21 @aozalevsky

**Comment by benmwebb** [comment]
This sounds like user error to me. `struct_ref` is already populated from per-Entity information (namely, `Reference` objects): https://python-ihm.readthedocs.io/en/latest/main.html#ihm.Entity

There's nothing currently to stop a user from adding multiple identical references, just as they can add multiple identical rows to the mmCIF table. We certainly could remove duplicates (we do for datasets, for example) although I don't generally like to go behind the user's back this way.

**Comment by brindakv** [comment]
Thanks @benmwebb. 

Once this is incorrectly created at deposition, it is very difficult for curators to fix post-deposition for a large entry with many chains belonging to the same entity. Considering the effort it takes, I would prefer for this to enforced at the software level.

**Comment by aozalevsky** [comment]
@benmwebb 

I'm looking at  @neeleshsoni21 's code right now. 

https://github.com/integrativemodeling/NPC_Basket/blob/7511ffd167203d4fe93fcdb34b6ae17b9b0a1487/Yeast_NPC_Basket/src/modeling_basket.py#L369-L425

https://github.com/integrativemodeling/NPC_Basket/blob/7511ffd167203d4fe93fcdb34b6ae17b9b0a1487/Yeast_NPC_Basket/src/modeling_basket.py#L601-L634

The duplication routines don't seem immediately wrong to me.  Yet they generate 2 and 16 `_struct_ref` records correspondingly. 

Is there a different (proper?) way to add multiple instances of the same molecule?

**Comment by benmwebb** [comment]
That code looks fine for setting up the subunits. But that's not responsible for populating `struct_ref`. IMP doesn't care where your input sequences come from (PMI *can* extract a UniProt accession from the FASTA header, and store that in IMP's `Chain` decorator, but we generally don't do that). So usually at deposition time one needs to use the python-ihm API directly to add UniProt info. I don't see where @neeleshsoni21 is doing that in those scripts, but here's one example:
https://github.com/integrativemodeling/pol_ii_g/blob/main/production_scripts/sample.py#L288-L305

Note that that is done for only the first copy (`.0`) of each subunit. If, for example, you loop over all subunits instead of all entities then you may end up with duplicate references (I pointed this out in a recent deposition, don't remember if it was this one though).

We should probably touch on this in the [deposition tutorial](https://integrativemodeling.org/tutorials/deposition/); I'll open an issue.
