### ISSUE TITLE
pdbx_poly_seq_scheme for beaded residues is incorrectly populated

### ISSUE THREAD

**Issue by brindakv** [ihmwg/python-ihm#150]
In coarse-grained models with coordinates in `ihm_sphere_obj_site`, when the full sequence of an entity is included in `entity_poly` and `entity_poly_seq`, but a segment in not modeled and therefore not included in `ihm_sphere_obj_site`, the `pdbx_poly_seq_scheme` is populated incorrectly and shows that the entire sequence is modeled. For example, `_pdbx_poly_seq_scheme.auth_seq_num` and `_pdbx_poly_seq_scheme.auth_seq_num` should have `?`. 

See https://files.rcsb.org/view/8QB4.cif for an example for `pdbx_poly_seq_scheme` when `atom_site` has missing residues.

**Comment by benmwebb** [comment]
I don't think this would be specific to coarse-grained models, since python-ihm tracks the mapping between seq_id and auth_seq_num in the asym, not in the atom or sphere objects. It wouldn't be possible to extract information on non-modeled residues at output time from the atom/sphere objects, since we don't enumerate those until after we've dumped all the entity and scheme tables, and we only enumerate them once by design (the Python interface is a generator, not a list). But what we could do is:

 1. If any seq_id is included in the `_ihm_residues_not_modeled` table for all models, emit `?` for  `_pdbx_poly_seq_scheme.auth_seq_num`, `.pdb_mon_id` and `.auth_mon_id`. (I would expect `.pdb_ins_code` to also be `?` but from your example it looks like `.` is used.)
 2. On read, have `make_mmcif` check all read-in atoms/spheres and add any non-modeled ranges to the `_ihm_residues_not_modeled` table if not already there.

Would that work?

**Comment by brindakv** [comment]
@benmwebb Yes, that would work.
