### ISSUE TITLE
Inconsistent `python-ihm` read/write behavior 

### ISSUE THREAD

**Issue by aozalevsky** [ihmwg/python-ihm#152]
Sometimes, I have to read/modify/write IHM-CIF files to make them compatible with molprobity. I know that `python-ihm` is not supposed to preserve the structure of the input file, but in some cases `ihm.dumper` simply fails to dump the content previously populated by `ihm.reader`. 

Here is a simple script i used to read/write an IHM-CIF file (without any modifications):
```python
#!/bin/env python3

import argparse
import ihm, ihm.dumper, ihm.reader

def parse_ihm_cif(fname, encoding='utf8') -> tuple:
    try: 
        with open(fname, 'r', encoding=encoding) as fh:
            system, = ihm.reader.read(fh)
    except UnicodeDecodeError:
        encoding = 'ascii'
        with open(fname, 'r', encoding=encoding, errors='ignore') as fh:
            system, = ihm.reader.read(fh)

    return(system, encoding)

def write_ihm_cif(fname, system, encoding='utf8'):
    with open(fname, 'w', encoding=encoding) as f:
        ihm.dumper.write(f, [system])

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        prog='IHM-CIF rewriter',
        description="Read/Write IHM-CIF file without any modifications")

    parser.add_argument('-i', '--input', required=True)
    parser.add_argument('-o', '--output', required=True)

    args = parser.parse_args()

    system, encoding = parse_ihm_cif(args.input)
    write_ihm_cif(args.output, system, encoding)
```

To be sure, i tried to run it twice (read/write/read/write), and a considerable number of entries failed with various errors. Here is a full [log](https://pastebin.com/Z2FqhP9X) (NB, if first write fails, the second read will fail too).

Affected version: 1.6
Affected IDs: 8zz8, 8zzd, 8zzi, 8zzu, 9a04, 9a0b, 9a0c, 9a0d, 9a0e, 9a0i, 9a0j, 9a0p, 9a0q, 9a0r, 9a0t, 9a0v, 9a0x, 9a0y, 9a13, 9a1s, 9a1t, 9a1z, 9a24, 9a25, 9a2d, 9a3p, 9a49, 9a82, 9a8g. 

I feel `ihm.reader` and `ihm.dumper` should perform identical consistency checks.

**Comment by benmwebb** [comment]
>  in some cases `ihm.dumper` simply fails to dump the content previously populated by `ihm.reader`.

This is by design. python-ihm should output, in most cases, dictionary-compliant files that are also internally consistent (e.g. representation that matches the assembly, which is not enforced by the dictionary but by the annotators). At the same time it attempts to read non-conformant files, e.g. those missing entity tables. These may need fixing up in some way before they can be output, which is what make_mmcif generally tries to do.

Looks like you have three main categories of issues here:
 1. Out-of-range residues
 2. Mismatch between entity and reference sequence
 3. Missing data, i.e. `None`

I will look through each of these but (1) and (2) may require the files to be remediated. python-ihm does more checks these days than it used to, so there may be some non-conformant files in the archive; @brindakv can opine on these. (3) may be genuine python-ihm bugs in some cases.

> To be sure, i tried to run it twice (read/write/read/write)

A second read doesn't make a whole lot of sense. These are all stream operations, so if the dumper hits an exception, you're going to end up with a truncated file. In most cases that won't read in again properly.

If you're trying to generate whatever mmCIF-like inputs Molprobity wants, you might want to write your own dumper (e.g. to ignore all information Molprobity doesn't read, perhaps just to output `atom_site` and some of the entity tables). If you want to use python-ihm to do that, you can set `e._range_check = False` for each Entity `e` to disable range checks and perhaps also `del e.references[:]` to throw away reference sequence information.

**Comment by aozalevsky** [comment]
> Python-ihm should output, in most cases, dictionary-compliant files that are also internally consistent (e.g., representation that matches the assembly, which is not enforced by the dictionary but by the annotators). At the same time it attempts to read non-conformant files, e.g. those missing entity tables.

My point is that after reading a (potentially non-conformant) file, the data structure in memory (after all on-the-fly fixes) might still be non-conformant. This will only be discovered during writing because writing performs additional checks. I believe the more consistent behavior would be if, after reading and making on-the-fly fixes, `python-ihm` ran the same checks as during/after the write.

**Comment by benmwebb** [comment]
> I feel `ihm.reader` and `ihm.dumper` should perform identical consistency checks.

This is now the case with #153; if `ihm.dumper.write()` is called with `check=False` then it will do the same consistency checks as `ihm.reader.read()` (i.e., none). With `check=False` python-ihm will now write out all of the reported archive IDs without errors, with the sole exception of `8zz8`, which has no sequence information.

With a couple of minor exceptions, python-ihm was correctly reporting data consistency issues with all of the reported IDs. I have passed these on to @brindakv for remediation.
