### ISSUE TITLE
Add pdbx_PDB_ins_code to AtomSite and write _atom_site.pdbx_PDB_ins_code in dump_atoms 

### ISSUE THREAD

**Issue by jkosinski** [ihmwg/python-ihm#65]
BioPython mmCIF parser, https://github.com/biopython/biopython/blob/master/Bio/PDB/MMCIFParser.py, requires _atom_site.pdbx_PDB_ins_code to be present but this field is not present in IHM's AtomSite and dumper, making the IHM files invalid for BioPython. Would it be possible to add pdbx_PDB_ins_code as an option?

**Comment by benmwebb** [comment]
This has to be a bug in BioPython and should be reported there. Insertion codes are not required in the PDBx dictionary: https://mmcif.wwpdb.org/dictionaries/mmcif_pdbx_v50.dic/Items/_atom_site.pdbx_PDB_ins_code.html

It would certainly be straightforward to write out `atom_site.pdbx_PDB_ins_code` but they would all be blank (at least for now) because we don't assign insertion codes.

**Comment by brindakv** [comment]
@benmwebb, `_atom_site.pdbx_PDB_ins_code` is not a mandatory field according to PDBx/mmCIF. However, it might be good to support reading and writing it out an as optional field.

**Comment by jkosinski** [comment]
I reported it to BioPython and they said would fix. But if no problem for
Ben to introduce it soon in python-ihm, that would be very helpful, as we
use python-ihm to generate CIFs for some pipelines which use biopython and
now crash (not sure how fast biopython will be as they have a longer list
of issues on the list ;-)

**Comment by benmwebb** [comment]
I already resolved and closed this issue; it was very straightforward to add.

**Comment by jkosinski** [comment]
Thanks Ben!!
